### ISSUE TITLE
configuring migration_primary_key & migration_foreign_key can cause an issue. 

### ISSUE THREAD

**Issue by Tzelon** [benstepp/ecto_ksuid#3]
Hey there,
in this guide https://github.com/benstepp/ecto_ksuid/blob/main/guides/using_ksuid_as_default.md
it says we need to configure migration_primary_key & migration_foreign_key with `name: :id` and `type: :"char(27)"`.
configuring the name can cause an issue with duplicate constraints. 
Ecto default behavior is to create a unique name with "#{table}_#{column}_fkey". 

I would recommend updating the guide and removing the `name: :id`

Thank you for the library.

**Comment by benstepp** [comment]
Thanks! I removed the `name` from the docs for the `migration_foreign_key`.
